[server]
name = "4get"
short_description = "4get — Privacy-focused metasearch engine."
long_description = ""
default_theme = "Dark"
host = "127.0.0.1"
port = 3001
data_dir = "data"
user_agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:151.0) Gecko/20100101 Firefox/151.0"
user_agent_friendly = "4get-search (+https://search.sorvx.com)"
api_enabled = true
instances = [
    "https://4get.ca",
    "https://4get.zzls.xyz",
]
alt_addresses = []

[bot_protection]
enabled = 0
max_searches = 100
header_regex = "bot|wget|curl|python-requests|scrapy|go-http-client|ruby|yahoo|spider|qwant|meta"
filtered_header_keys = []
captcha_dataset = []

[scrapers]
google_cx_endpoint = ""
marginalia_api_key = ""
yep_use_api = false

[oracles]
enabled = true

[proxies]
